In [1]:
import pandas as pd

In [3]:
milk_prod_data_Arizona = pd.read_csv('../data/Milk production per cow- Arizona.csv')

In [4]:
print(len(milk_prod_data_Arizona))

238

In [5]:
milk_prod_data_Arizona.head()

,state-name,month,season,season and year,quadrant,quadrant + year,milk production per cow,avg heat index
0,ARIZONA,1/2006,Winter,Winter 2006,Q1,Q1 2006,"2,045",NaN
1,ARIZONA,2/2006,Winter,Winter 2006,Q1,Q1 2006,"1,940",NaN
2,ARIZONA,3/2006,Spring,Spring 2006,Q1,Q1 2006,"2,190",NaN
3,ARIZONA,4/2006,Spring,Spring 2006,Q2,Q2 2006,"2,145",NaN
4,ARIZONA,5/2006,Spring,Spring 2006,Q2,Q2 2006,"2,155",NaN

In [23]:
new_milk_prod_Arizona = milk_prod_data_Arizona.drop(columns=['season','quadrant '])

In [21]:
new_milk_prod_Arizona = milk_prod_data_Arizona.drop(columns=['quadrant '])

In [13]:
new_milk_prod_Arizona.columns

Index(['state-name', 'month', 'season and year', 'quadrant ',
       'quadrant + year', 'milk production per cow', 'avg heat index'],
      dtype='str')

In [82]:
new_milk_prod_Arizona.head()

,state-name,month,season and year,quadrant + year,milk production per cow,avg heat index
0,ARIZONA,1/2006,Winter 2006,Q1 2006,"2,045",NaN
1,ARIZONA,2/2006,Winter 2006,Q1 2006,"1,940",NaN
2,ARIZONA,3/2006,Spring 2006,Q1 2006,"2,190",NaN
3,ARIZONA,4/2006,Spring 2006,Q2 2006,"2,145",NaN
4,ARIZONA,5/2006,Spring 2006,Q2 2006,"2,155",NaN

In [33]:
heat_data_Arizona = pd.read_csv('../data/Arizona Max Temperature - Sheet1.csv')

In [79]:
heat_data_Arizona.tail

<bound method NDFrame.tail of        Date  Value (Fahrenheit)
0    200601                59.0
1    200602                63.6
2    200603                61.0
3    200604                74.6
4    200605                87.0
..      ...                 ...
238  202511                68.3
239  202512                63.6
240  202601                58.2
241  202602                66.2
242  202603                79.9

[243 rows x 2 columns]>

In [84]:
#Joining the two datasets# 
arizona_heat_milk = new_milk_prod_Arizona.concat(['heat_data_Arizona'])

AttributeError: 'DataFrame' object has no attribute 'concat'

In [86]:
arizona_heat_milk = pd.concat([new_milk_prod_Arizona, heat_data_Arizona], axis=1)

In [95]:
print(arizona_heat_milk.iloc[[234]])

    state-name    month season and year quadrant + year  \
234    ARIZONA  11/2025     Autumn 2025         Q4 2025

    milk production per cow  avg heat index    Date  Value (Fahrenheit)
234                   1,955             NaN  202507                96.1

In [ ]:
#calling this problem as I want my month and date to be the same format so then I can see where my dates starts to be weird#
arizona_data_problem = arizona_heat_milk[['month', 'Date']]

In [ ]:
# identify where is my problem#
print (arizona_data_problem.iloc[['85','86']])

     month    Date
85  2/2013  201302
86  7/2013  201303

In [96]:
arizona_heat_milk.to_csv('../data/arizona_heat_milk.csv')

In [38]:
milk_prod_data_Iowa = pd.read_csv('../data/Milk production per cow- Iowa.csv')

In [39]:
milk_prod_data_Iowa.head()

,state-name,month,season,season and year,quadrant,quadrant + year,milk production per cow,avg heat index
0,IOWA,1/2006,Winter,Winter 2006,Q1,Q1 2006,"1,750",NaN
1,IOWA,2/2006,Winter,Winter 2006,Q1,Q1 2006,"1,610",NaN
2,IOWA,3/2006,Spring,Spring 2006,Q1,Q1 2006,"1,780",NaN
3,IOWA,4/2006,Spring,Spring 2006,Q2,Q2 2006,"1,735",NaN
4,IOWA,5/2006,Spring,Spring 2006,Q2,Q2 2006,"1,765",NaN

In [40]:
heat_data_Iowa = pd.read_csv('../data/max Temp sheet - iowa.csv')

In [44]:
heat_data_Iowa.tail

<bound method NDFrame.tail of        Date  Value
0    200601   39.9
1    200602   36.2
2    200603   45.8
3    200604   65.9
4    200605   71.7
..      ...    ...
238  202511   49.4
239  202512   33.0
240  202601   28.4
241  202602   43.6
242  202603   55.6

[243 rows x 2 columns]>

In [97]:
#Joining the two datasets for heat and milk production for Iowa#
Iowa_heat_milk = pd.concat([milk_prod_data_Iowa,heat_data_Iowa], axis=1)
#pd.concat([new_milk_prod_Arizona, heat_data_Arizona], axis=1)3

In [99]:
Iowa_heat_milk.head()

,state-name,month,season,season and year,quadrant,quadrant + year,milk production per cow,avg heat index,Date,Value
0,IOWA,1/2006,Winter,Winter 2006,Q1,Q1 2006,"1,750",NaN,200601,39.9
1,IOWA,2/2006,Winter,Winter 2006,Q1,Q1 2006,"1,610",NaN,200602,36.2
2,IOWA,3/2006,Spring,Spring 2006,Q1,Q1 2006,"1,780",NaN,200603,45.8
3,IOWA,4/2006,Spring,Spring 2006,Q2,Q2 2006,"1,735",NaN,200604,65.9
4,IOWA,5/2006,Spring,Spring 2006,Q2,Q2 2006,"1,765",NaN,200605,71.7

In [100]:
Iowa_heat_milk.drop(columns=['season','quadrant '])

,state-name,month,season and year,quadrant + year,milk production per cow,avg heat index,Date,Value
0,IOWA,1/2006,Winter 2006,Q1 2006,"1,750",NaN,200601,39.9
1,IOWA,2/2006,Winter 2006,Q1 2006,"1,610",NaN,200602,36.2
2,IOWA,3/2006,Spring 2006,Q1 2006,"1,780",NaN,200603,45.8
3,IOWA,4/2006,Spring 2006,Q2 2006,"1,735",NaN,200604,65.9
4,IOWA,5/2006,Spring 2006,Q2 2006,"1,765",NaN,200605,71.7
...,...,...,...,...,...,...,...,...
238,NaN,NaN,NaN,NaN,NaN,NaN,202511,49.4
239,NaN,NaN,NaN,NaN,NaN,NaN,202512,33.0
240,NaN,NaN,NaN,NaN,NaN,NaN,202601,28.4
241,NaN,NaN,NaN,NaN,NaN,NaN,202602,43.6
242,NaN,NaN,NaN,NaN,NaN,NaN,202603,55.6

In [101]:
Iowa_heat_milk.to_csv('../data/Iowa_heat_milk.csv')

In [ ]:
# putting two datasets for Kansas together#
milk_prod_data_Kansas = pd.read_csv('../data/Milk production per cow- Kansas.csv')

In [73]:
milk_prod_data_Kansas.head

<bound method NDFrame.head of     state-name    month  season season and year quadrant  quadrant + year  \
0       Kansas   1/2006  Winter     Winter 2006        Q1         Q1 2006
1       Kansas   2/2006  Winter     Winter 2006        Q1         Q1 2006
2       Kansas   3/2006  Spring     Spring 2006        Q1         Q1 2006
3       Kansas   4/2006  Spring     Spring 2006        Q2         Q2 2006
4       Kansas   5/2006  Spring     Spring 2006        Q2         Q2 2006
..         ...      ...     ...             ...       ...             ...
233     Kansas  10/2025  Autumn     Autumn 2025        Q4         Q4 2025
234     Kansas  11/2025  Autumn     Autumn 2025        Q4         Q4 2025
235     Kansas  12/2025  Winter     Winter 2025        Q4         Q4 2025
236     Kansas   1/2026  Winter     Winter 2026        Q1         Q1 2026
237     Kansas   2/2026  Winter     Winter 2026        Q1         Q1 2026

    milk production per cow  avg heat index
0                     1,790             NaN
1                     1,650             NaN
2                     1,840             NaN
3                     1,810             NaN
4                     1,870             NaN
..                      ...             ...
233                   2,020             NaN
234                   1,955             NaN
235                   2,015             NaN
236                   2,045             NaN
237                   1,875             NaN

[238 rows x 8 columns]>

In [76]:
#upload heat Data
heat_data_Kansas = pd.read_csv('../data/max Temp sheet- Kansas Max Temp.csv')
heat_data_Kansas.head

<bound method NDFrame.head of        Date  Value
0    200601   55.5
1    200602   49.1
2    200603   58.3
3    200604   74.9
4    200605   79.0
..      ...    ...
238  202511   60.7
239  202512   51.5
240  202601   44.6
241  202602   59.0
242  202603   69.1

[243 rows x 2 columns]>

In [103]:
Kansas_heat_milk = pd.concat([milk_prod_data_Kansas, heat_data_Kansas], axis=1)

In [104]:
Kansas_heat_milk.head

<bound method NDFrame.head of     state-name   month  season season and year quadrant  quadrant + year  \
0       Kansas  1/2006  Winter     Winter 2006        Q1         Q1 2006
1       Kansas  2/2006  Winter     Winter 2006        Q1         Q1 2006
2       Kansas  3/2006  Spring     Spring 2006        Q1         Q1 2006
3       Kansas  4/2006  Spring     Spring 2006        Q2         Q2 2006
4       Kansas  5/2006  Spring     Spring 2006        Q2         Q2 2006
..         ...     ...     ...             ...       ...             ...
238        NaN     NaN     NaN             NaN       NaN             NaN
239        NaN     NaN     NaN             NaN       NaN             NaN
240        NaN     NaN     NaN             NaN       NaN             NaN
241        NaN     NaN     NaN             NaN       NaN             NaN
242        NaN     NaN     NaN             NaN       NaN             NaN

    milk production per cow  avg heat index    Date  Value
0                     1,790             NaN  200601   55.5
1                     1,650             NaN  200602   49.1
2                     1,840             NaN  200603   58.3
3                     1,810             NaN  200604   74.9
4                     1,870             NaN  200605   79.0
..                      ...             ...     ...    ...
238                     NaN             NaN  202511   60.7
239                     NaN             NaN  202512   51.5
240                     NaN             NaN  202601   44.6
241                     NaN             NaN  202602   59.0
242                     NaN             NaN  202603   69.1

[243 rows x 10 columns]>

In [ ]:
#uploading the Kansas dataset to csv#
Kansas_heat_milk.to_csv('../data/Kansas_heat_milk.csv')

In [ ]:
#uploading milk prod Data NY#
milk_prod_data_NY = pd.read_csv('../data/Milk production per cow- New York.csv')

In [ ]:
#uploading heat data NY#
heat_data_NY = pd.read_csv('../data/max Temp sheet - New York.csv')

In [110]:
NY_heat_milk = pd.concat([milk_prod_data_NY, heat_data_NY], axis=1)

In [112]:
NY_heat_milk.tail

<bound method NDFrame.tail of     state-name   month  season season and year quadrant  quadrant + year  \
0     New York  1/2006  Winter     Winter 2006        Q1         Q1 2006
1     New York  2/2006  Winter     Winter 2006        Q1         Q1 2006
2     New York  3/2006  Spring     Spring 2006        Q1         Q1 2006
3     New York  4/2006  Spring     Spring 2006        Q2         Q2 2006
4     New York  5/2006  Spring     Spring 2006        Q2         Q2 2006
..         ...     ...     ...             ...       ...             ...
238        NaN     NaN     NaN             NaN       NaN             NaN
239        NaN     NaN     NaN             NaN       NaN             NaN
240        NaN     NaN     NaN             NaN       NaN             NaN
241        NaN     NaN     NaN             NaN       NaN             NaN
242        NaN     NaN     NaN             NaN       NaN             NaN

    milk production per cow  avg heat index    Date  Value
0                     1,595             NaN  200601   38.7
1                     1,475             NaN  200602   33.3
2                     1,630             NaN  200603   41.1
3                     1,590             NaN  200604   57.8
4                     1,660             NaN  200605   66.7
..                      ...             ...     ...    ...
238                     NaN             NaN  202511   43.6
239                     NaN             NaN  202512   31.6
240                     NaN             NaN  202601   26.4
241                     NaN             NaN  202602   29.6
242                     NaN             NaN  202603   46.4

[243 rows x 10 columns]>

In [ ]:
#uploading NY data for heat and milk production into same dataset to a CSV file#
NY_heat_milk.to_csv('../data/NY_heat_milk.csv')

In [ ]:
#uploading the milk prod from New Mexico
NM_milk_prod = pd.read_csv('../data/Milk production per cow- New Mexico.csv')

In [116]:
NM_milk_prod.tail()

,state-name,month,season,season and year,quadrant,quadrant + year,milk production per cow,avg heat index
233,New Mexico,10/2025,Autumn,Autumn 2025,Q4,Q4 2025,"2,020",NaN
234,New Mexico,11/2025,Autumn,Autumn 2025,Q4,Q4 2025,"1,955",NaN
235,New Mexico,12/2025,Winter,Winter 2025,Q4,Q4 2025,"2,050",NaN
236,New Mexico,1/2026,Winter,Winter 2026,Q1,Q1 2026,"2,115",NaN
237,New Mexico,2/2026,Winter,Winter 2026,Q1,Q1 2026,"1,970",NaN

In [117]:
#uploading NM heat data#
NM_heat_data = pd.read_csv('../data/max Temp sheet - New Mexico.csv')

In [118]:
NM_heat_data.tail()

       Date  Value
238  202511   64.1
239  202512   59.3
240  202601   50.9
241  202602   61.2
242  202603   74.1

In [120]:
NM_heat_milk = pd.concat([NM_milk_prod, heat_data_NY], axis=1)

In [121]:
NM_heat_milk.tail()

,state-name,month,season,season and year,quadrant,quadrant + year,milk production per cow,avg heat index,Date,Value
238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202511,43.6
239,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202512,31.6
240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202601,26.4
241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202602,29.6
242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202603,46.4

In [122]:
NM_heat_milk.to_csv('../data/NM_heat_milk.csv')

In [ ]:
#importing Texas milk pro #
Texas_milk_prod = pd.read_csv('../data/Milk production per cow- Texas.csv')

In [127]:
Texas_milk_prod.sample

<bound method NDFrame.sample of     state-name    month  season season and year quadrant  quadrant + year  \
0        Texas   1/2006  Winter     Winter 2006        Q1         Q1 2006
1        Texas   2/2006  Winter     Winter 2006        Q1         Q1 2006
2        Texas   3/2006  Spring     Spring 2006        Q1         Q1 2006
3        Texas   4/2006  Spring     Spring 2006        Q2         Q2 2006
4        Texas   5/2006  Spring     Spring 2006        Q2         Q2 2006
..         ...      ...     ...             ...       ...             ...
233      Texas  10/2025  Autumn     Autumn 2025        Q4         Q4 2025
234      Texas  11/2025  Autumn     Autumn 2025        Q4         Q4 2025
235      Texas  12/2025  Winter     Winter 2025        Q4         Q4 2025
236      Texas   1/2026  Winter     Winter 2026        Q1         Q1 2026
237      Texas   2/2026  Winter     Winter 2026        Q1         Q1 2026

    milk production per cow  avg heat index
0                     1,705             NaN
1                     1,600             NaN
2                     1,825             NaN
3                     1,750             NaN
4                     1,790             NaN
..                      ...             ...
233                   2,205             NaN
234                   2,125             NaN
235                   2,205             NaN
236                   2,235             NaN
237                   2,045             NaN

[238 rows x 8 columns]>

In [ ]:
#importing Texas heat data#
Texas_heat_data = pd.read_csv('../data/max Temp sheet - Texas.csv')

In [126]:
Texas_heat_data.sample

<bound method NDFrame.sample of        Date  Value
0    200601   68.3
1    200602   64.2
2    200603   73.5
3    200604   84.4
4    200605   89.3
..      ...    ...
238  202511   75.9
239  202512   67.0
240  202601   61.1
241  202602   73.0
242  202603   81.4

[243 rows x 2 columns]>

In [ ]:
#creating the combined file w both heat data and milk prod data for Texas #
Texas_heat_milk = pd.concat([Texas_milk_prod, Texas_heat_data], axis=1)

In [130]:
#uploading to a csv file# 
Texas_heat_milk.to_csv('../data/Texas_heat_milk.csv')